---
- name: Install multiple packages on Devices
  hosts: Devices
  become: true
  tasks:
    - name: Update the apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache is considered valid for 1 hour

    - name: Install packages
      ansible.builtin.apt:
        name:
          - nmap
          - neofetch
          - micro
        state: present
